### ISSUE TITLE
fail to luanch jvm

### ISSUE THREAD

**Issue by ZKsolar** [MikeWang000000/ChxUtility#4]

**Comment by licsber** [comment]
please add more infomation, such as jvm version (does 11)?

**Comment by rosefo** [comment]
安装好jdk后,配置完毕环境变量,cmd java正常,打开使用提示fail to luanch jvm

**Comment by MikeWang000000** [comment]
> 安装好jdk后,配置完毕环境变量,cmd java正常,打开使用提示fail to luanch jvm

使用以下命令运行：
```bash
java -jar ./ChxGUI-1.0.jar
```

**需要注意的是，JDK 版本应该为 11 。**

由于本人已经毕业，这个工具的开发已经趋于停滞，超星的登录接口可能已经发生了改变，推荐使用类似的其他工具。
当然，也欢迎提PR，检查通过后我会合并到主分支。

**Comment by Janet-Baker** [comment]
```
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:66)
	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
	at net.vomega.chx.ChxUtility.loadAccountInfo(ChxUtility.java:192)
	at net.vomega.chx.ChxUtility.login(ChxUtility.java:167)
	at net.vomega.chx.ChxGUI.prepareChx(ChxGUI.java:447)
	at net.vomega.chx.ChxGUI.run(ChxGUI.java:53)
	at net.vomega.chx.ChxGUI.main(ChxGUI.java:547)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1405)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:543)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:61)
	... 6 more
```
